### ISSUE TITLE
Error attempting to migrate from CentOS 7 VM to CentOS container host

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/prototype#2]
Attempting to follow the instructions from the PR in #1, I get the following error from `migrate-machine`:

```
$ sudo ./leapp-tool.py migrate-machine -t rhel7-target rhel6-app-vm
[sudo] password for ncoghlan: 
! looking up "rhel6-app-vm" as source and "rhel7-target" as target
! obtaining SSH keys
Traceback (most recent call last):
  File "./leapp-tool.py", line 131, in <module>
    ssh = _get_ssh_config()
  File "./leapp-tool.py", line 17, in _get_ssh_config
    for x in check_output(['vagrant', 'ssh-config'], cwd=path).decode('utf-8').splitlines()[1:-1]]
  File "/usr/lib64/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/root/leapp-to/rhel6-guest-lamp'
```

I'm guessing I'm missing a setup step somewhere.

**Comment by shaded-enmity** [comment]
Ah yes, bad paths (cucos-02 ones), should be fixed now. Thanks

**Comment by shaded-enmity** [comment]
Also the relative path used in the script assumes that $PWD == the repo checkout. This could be handled better I suppose, but it's a side effect from using Vagrant, and it keeps the CLI usage from becoming too verbose.

**Comment by shaded-enmity** [comment]
Updated `cockpit.spawn` to reflect that: 104e751
